### ISSUE TITLE
ACOLITE CLI `--retrieve_luts` does not pull reverse LUTs for S2C_MSI_V4

### ISSUE THREAD

**Issue by bwakefie** [acolite/acolite#94]
I'm not entirely sure this is a bug: when using `v20250114.0`, if I execute `python launch_acolite.py --retrieve_luts --sensor S2C_MSI_V4` I notice two things:

- I need to specify `S2C_MSI_V4` (whereas the other sensors will work with `S2A_MSI` or `S2B_MSI` - I don't understand the difference between V4, I just noticed the behavior is different for `S2C_MSI_V4`)
- The LUTs that should be pulled from the corresponding [ACOLITE-LUT-202110-Reverse/S2C_MSI_V4](https://github.com/acolite/acolite_luts/tree/main/ACOLITE-LUT-202110-Reverse/S2C_MSI_V4) directory are not there. If I first run `python launch_acolite.py --retrieve_luts --sensor S2C_MSI_V4` this does download the LUTs in the [ACOLITE-LUT-202110/S2C_MSI_V4](https://github.com/acolite/acolite_luts/tree/main/ACOLITE-LUT-202110/S2C_MSI_V4) directory as expected, however the missing LUTs are downloaded at runtime when I later execute `python launch_acolite.py --cli --settings settings --inputfile="/path/to/S2/SAFE/package"`

Perhaps the reverse LUTs are not included here? https://github.com/acolite/acolite/blob/main/acolite/acolite/acolite_luts.py#L70

Let me know if I can provide any other helpful info/digging

**Comment by acolite** [comment]
Thanks for the report Brendan - indeed the acolite_luts script was in need of an update to support S2C_MSI and RSR versioning. I have now committed the change which should determine the RSR version from the settings file, and which includes a config file list of sensors with reverse LUTs. This will be integrated in the next release, which is probably not too far away since there were some other S2C related bugs.

In the new version the V4 LUT should be retrieved by:

`python launch_acolite.py --retrieve_luts --sensor S2C_MSI `

Quinten

**Comment by bwakefie** [comment]
Amazing, thanks for the quick patch Quinten! It's much appreciated. I'll pull the latest version and let you know if I'm still missing S2C LUTs being downloaded at runtime

**Comment by bwakefie** [comment]
Hi Quinten, I recently tested the command `python ./acolite/launch_acolite.py --retrieve_luts --sensor S2C_MSI` and it's appearing to work well! However, when run on the `L8_OLI` sensor with `python ./acolite/launch_acolite.py --retrieve_luts --sensor L8_OLI` I receive this error:

```
bash-5.2# python ./acolite/launch_acolite.py --retrieve_luts --sensor L8_OLI
Traceback (most recent call last):
  File "//./acolite/launch_acolite.py", line 84, in <module>
    launch_acolite()
  File "//./acolite/launch_acolite.py", line 51, in launch_acolite
    ac.acolite.acolite_luts(sensor=args.sensor)
  File "/acolite/acolite/acolite/acolite_luts.py", line 41, in acolite_luts
    if setd['rsr_version'] is not None: lut_sensor = '{}_{}'.format(s, setd['rsr_version'])
       ~~~~^^^^^^^^^^^^^^^
KeyError: 'rsr_version'
bash-5.2#
```

Is the `L8_OLI` sensor still compatible with the latest versions of S2 images?

**Comment by bwakefie** [comment]
It appears actually now if I use the `main` branch I can _only_ retrieve LUTS for `S2C_MSI` and I get the above error for `S2A_MSI`, `S2B_MSI` and `L8_OLI`

**Comment by bwakefie** [comment]
Ah, I see that `setd['rsr_version']` is assigned a value in [line 41](https://github.com/acolite/acolite/commit/090a791bf298a9a5d8294027b3ae65798461f21e#diff-3ce324189e7744a3b95cb62e61749504eb22d97897fffc846fc4737ea385d3fcR39) - does this mean there needs to be a value set

**Comment by bwakefie** [comment]
Oof, I accidentally closed this issue, that was a mistake

**Comment by acolite** [comment]
Hi Brendan, the latest commit hopefully fixes this issue. 

Quinten

**Comment by bwakefie** [comment]
Thanks Quinten! I can confirm that as of today, executing the command off the `main` branch is successful:
```
git clone --depth 1 --branch main https://github.com/acolite/acolite &&
python ./acolite/launch_acolite.py \
        --cli \
        --retrieve_luts \
        --sensor "L8_OLI, S2A_MSI, S2B_MSI, S2C_MSI"
```
(note: I added the `--cli` flag since I learning of its existence this week, but it has never been necessary for me when running `--retrieve_luts`)

**Comment by acolite** [comment]
Thanks for testing!

--cli is not needed for --retrieve_luts, as the latter does only that

Quinten
